version: '3'

services:
  solr:
    image: solr:9.2.1
    ports:
      - 5005:5005
      - 8983:8983
    environment:
      SOLR_OPTS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
    volumes:
      - ./data:/var/solr/data
    healthcheck:
      test: [ "CMD-SHELL", "curl -s http://localhost:8983/solr/" ]
      interval: 5s
      timeout: 5s
      retries: 30
